#pragma once

/**
 * The list of event types that can occur.
 */
enum EventType
{
	EVENT_LEFT_MOUSE_CLICK,
	EVENT_LEFT_MOUSE_DRAG,
	EVENT_LEFT_MOUSE_HOLD,
	EVENT_LEFT_MOUSE_RELEASE,
	EVENT_LEFT_MOUSE_CLICK_DOUBLE,
	EVENT_RIGHT_MOUSE_CLICK
};